### ISSUE TITLE
Sample Subscription YAML - timeWindow

### ISSUE THREAD

**Issue by harryli256** [open-cluster-management/rhacm-docs#248]
## Documentation Report

The YAML samples for creating a subscription that include a "timeWindow" should not be indented.

They should be the root element.

https://github.com/open-cluster-management/rhacm-docs/blob/doc_stage/manage_applications/managing_subscriptions.md

## Product release(s)
- [ ] [ACM 4.4] 

**Note:** ID will update the current version and the two previous versions (n-2). For earlier versions, we will address only P1 & P2 Doc APARS for releases in support.

## Type of documentation change

- [ ] New topic
- [x] Update to an existing topic

## Link to the topic(s) that require an update

* https://github.com/open-cluster-management/rhacm-docs/blob/doc_stage/manage_applications/managing_subscriptions.md

## Draft content or detailed description to get ID started

```
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: nginx
  namespace: my-channel-subscription-nginx
  labels:
    app: nginx-app-details
spec:
  channel: my-channel-namespace/my-development-channel
  name: nginx-ingress
  packageFilter:
    version: "1.20.x"
  placement:
    placementRef:
      kind: PlacementRule
      name: my-placement-rule
  **timeWindow:
    type: "block"/"active"
    location: "America/Los_Angeles"
    daysofweek: ["Monday", "Wednesday", "Friday"]
    hours:
      - start: "10:20AM"
        end: "10:30AM"
      - start: "12:40PM"
        end: "1:40PM"**
```

```
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name:
  namespace:
  labels:
spec:
  sourceNamespace:
  source:
  channel:
  name:
  packageFilter:
    version:  
    labelSelector:
      matchLabels:  
        package:
        component:
    annotations:  
  packageOverrides:
  - packageName:
    packageAlias:
    - path:
      value:
  placement:
    local:
    clusters:
      name:
    clusterSelector:
    placementRef:
      name:
      kind: PlacementRule
  overrides:
    clusterName:
    clusterOverrides:
      path:
      value:
  **timeWindow:
    type:
    location:
    daysofweek:
    hours:
      - start:
        end:**
```
